export const palaceData = {
  palaces: [
    {
      id: 1,
      name: "明清紫禁城",
      dynasty: "明、清",
      area: 72,
      houses: 8700,
      startYear: 1406,
      endYear: 1924,
      location: { lat: 39.9163, lng: 116.3972 },
      layout: { outerCourt: 60, innerCourt: 30, garden: 10 },
      image: new URL("../assets/images/明清紫禁城1.jpg", import.meta.url).href,
      description:
        "紫禁城是明清两代24位皇帝的皇宫，占地72万平方米，建筑面积约15万平方米，拥有大小宫殿70多座，房屋8700余间，是中国现存规模最大、保存最为完整的木质结构古建筑群。",
      highlights: [
        "世界现存最大木质结构古建筑群",
        "明清两代24位皇帝居住和处理朝政之所",
        "1987年列入《世界遗产名录》",
        "中国第一批全国重点文物保护单位",
      ],
      architecturalFeatures: [
        "严格的中轴对称布局",
        "前朝后寝的建筑格局",
        "黄色琉璃瓦屋顶",
        "红墙黄瓦的标志性色彩",
      ],
      notableBuildings: [
        {
          name: "太和殿",
          function: "皇帝举行大典场所",
          features: "殿内面积2377平方米，高26.92米",
        },
        {
          name: "乾清宫",
          function: "皇帝处理政务之所",
          features: "殿内悬挂正大光明匾额",
        },
        { name: "坤宁宫", function: "皇后寝宫", features: "清代改为祭祀场所" },
        {
          name: "御花园",
          function: "皇家园林",
          features: "占地12000平方米，有古松柏百余株",
        },
      ],
      culturalHeritage: [
        "馆藏文物186万余件",
        "《清明上河图》等稀世珍宝",
        "清代皇室生活用品",
        "古代宫廷文献档案",
      ],
    },
    {
      id: 2,
      name: "唐代大明宫",
      dynasty: "唐",
      area: 320,
      houses: 4000,
      startYear: 634,
      endYear: 904,
      location: { lat: 34.2733, lng: 108.9667 },
      layout: { outerCourt: 55, innerCourt: 35, garden: 10 },
      image: new URL("../assets/images/唐代大明宫1.jpg", import.meta.url).href,
      description:
        "大明宫是唐朝皇帝处理朝政和生活起居的场所，位于长安城东北角，始建于唐太宗时期，历时近30年建成。大明宫气势恢宏、规模巨大，是唐代盛世的标志性建筑，被誉为'盛唐之冠'。",
      highlights: [
        "盛唐文明的象征",
        "中国古代宫殿建筑的巅峰之作",
        "对日本、朝鲜等亚洲国家建筑影响深远",
        "众多唐诗以此为题",
      ],
      architecturalFeatures: [
        "三出阙的建筑形制",
        "含元殿高耸入云",
        "太液池皇家园林水景",
        "丹凤门为宫城正门",
      ],
      notableBuildings: [
        {
          name: "含元殿",
          function: "举行大典场所",
          features: "殿基高于地面15米，气势恢宏",
        },
        {
          name: "麟德殿",
          function: "接见外国使节",
          features: "皇帝赐宴之所，可容千人",
        },
        {
          name: "太液池",
          function: "皇家园林水景",
          features: "池中有蓬莱、方丈、瀛洲三岛",
        },
        {
          name: "翰林院",
          function: "文人学士聚集之地",
          features: "唐代文化繁荣的见证",
        },
      ],
      culturalHeritage: [
        "唐代壁画珍品",
        "金银器工艺品",
        "唐三彩文物",
        "丝路文化交流见证",
      ],
    },
    {
      id: 3,
      name: "元代大都皇宫",
      dynasty: "元",
      area: 480,
      houses: 4000,
      startYear: 1267,
      endYear: 1368,
      location: { lat: 39.9042, lng: 116.4074 },
      layout: { outerCourt: 50, innerCourt: 40, garden: 10 },
      image: new URL("../assets/images/元代大都皇宫1.jpg", import.meta.url)
        .href,
      description:
        "元代大都皇宫是元朝帝国的政治中心，位于今天的北京市。皇宫融合了汉族、蒙古族、藏族等多民族文化元素，体现了中华文明多元一体的特点，为后来明清紫禁城的设计提供了重要参考。",
      highlights: [
        "元朝大一统帝国的象征",
        "蒙古族与汉族文化融合的见证",
        "元大都城市规划的核心",
        "对北京城市布局影响深远",
      ],
      architecturalFeatures: [
        "体现了民族融合特色",
        "布局借鉴汉族传统宫殿规制",
        "吸收了草原民族帐幕元素",
        "整体规划影响后世都城建设",
      ],
      notableBuildings: [
        {
          name: "大内",
          function: "皇宫核心区域",
          features: "皇帝处理朝政之所",
        },
        { name: "延春阁", function: "皇帝寝宫", features: "蒙古族风格建筑" },
        { name: "大明殿", function: "举行大典", features: "宫内最大宫殿建筑" },
      ],
      culturalHeritage: [
        "元代壁画艺术珍品",
        "蒙汉合壁的工艺品",
        "元青花瓷器收藏",
        "马可波罗游记的见证",
      ],
    },
    {
      id: 4,
      name: "宋代东京皇宫",
      dynasty: "北宋",
      area: 250,
      houses: 5000,
      startYear: 962,
      endYear: 1127,
      location: { lat: 34.8036, lng: 114.3072 },
      layout: { outerCourt: 52, innerCourt: 38, garden: 10 },
      image: new URL("../assets/images/宋代东京皇宫1.jpg", import.meta.url)
        .href,
      description:
        "宋代东京皇宫位于当时世界上最大的城市开封，是北宋时期的政治中心。皇宫建筑设计精致典雅，融合了南北建筑风格，见证了宋代高度发达的城市文明和建筑艺术水平。",
      highlights: [
        "当时世界最大城市的核心建筑",
        "宋代建筑美学的杰出代表",
        "《清明上河图》的创作背景",
        "见证北宋经济的繁荣",
      ],
      architecturalFeatures: [
        "布局严谨的中轴对称",
        "建筑风格精致典雅",
        "注重与御花园的融合",
        "体现了宋代审美趣味",
      ],
      notableBuildings: [
        { name: "文德殿", function: "举行大典场所", features: "皇宫主体建筑" },
        { name: "御花园", function: "皇家园林", features: "以水景和假山著称" },
        { name: "金水河", function: "宫内水系", features: "引汴河之水入宫" },
      ],
      culturalHeritage: [
        "宋代书画艺术珍品",
        "官窑瓷器收藏",
        "科技文献档案",
        "宋代市井文化见证",
      ],
    },
    {
      id: 5,
      name: "汉代未央宫",
      dynasty: "汉",
      area: 484,
      houses: 4000,
      startYear: -200,
      endYear: 190,
      location: { lat: 34.3233, lng: 108.9167 },
      layout: { outerCourt: 48, innerCourt: 42, garden: 10 },
      image: new URL("../assets/images/未央宫1.jpg", import.meta.url).href,
      description:
        "未央宫是西汉帝国的政治文化中心，位于长安城西南角。刘邦称帝后开始修建，是中国古代宫殿的典范之作。作为丝绸之路的起点，未央宫见证了汉朝与西域各国的交往，是中华文明与世界文明交流的重要窗口。",
      highlights: [
        "西汉帝国的政治文化中心",
        "丝绸之路的重要起点",
        "确立了汉代宫殿建筑范式",
        "见证汉武盛世的辉煌",
      ],
      architecturalFeatures: [
        "前殿坐北朝南的布局",
        "沧池水景园林",
        "天禄阁藏书楼",
        "规模宏大的宫城形制",
      ],
      notableBuildings: [
        {
          name: "前殿",
          function: "朝会听政之所",
          features: "宫殿主体建筑，高大宏伟",
        },
        {
          name: "天禄阁",
          function: "皇家藏书楼",
          features: "中国最早的图书馆之一",
        },
        { name: "沧池", function: "宫内水景", features: "宫苑结合的典范" },
        { name: "石渠阁", function: "国家档案馆", features: "收藏律令图籍" },
      ],
      culturalHeritage: [
        "汉代瓦当珍品",
        "鎏金铜器工艺",
        "汉代丝织品",
        "与西域文化交流的见证",
      ],
    },
    {
      id: 6,
      name: "隋代大兴宫",
      dynasty: "隋",
      area: 192,
      houses: 3500,
      startYear: 582,
      endYear: 662,
      location: { lat: 34.2633, lng: 108.9567 },
      layout: { outerCourt: 50, innerCourt: 40, garden: 10 },
      image: new URL("../assets/images/隋代大兴宫1.jpg", import.meta.url).href,
      description:
        "大兴宫是隋朝皇宫，开创了隋唐宫殿建筑的先河。虽然使用时间不长，但大兴宫的建筑规制和布局为唐代大明宫提供了重要参考，见证了隋朝大一统的辉煌。",
      highlights: [
        "隋唐宫殿建筑的开创者",
        "隋炀帝修建仁寿宫",
        "为盛唐建筑奠定基础",
        "见证隋朝兴衰历史",
      ],
      architecturalFeatures: [
        "布局规整对称",
        "单体建筑规模宏大",
        "开创宫殿建筑新范式",
        "园林与宫殿相结合",
      ],
      notableBuildings: [
        { name: "大兴殿", function: "正殿建筑", features: "举行大典场所" },
        { name: "仁寿宫", function: "皇家园林", features: "隋炀帝时期扩建" },
        { name: "武备库", function: "兵器储藏", features: "隋朝军事实力象征" },
      ],
      culturalHeritage: [
        "隋代建筑构件",
        "三彩艺术珍品",
        "开凿大运河的见证",
        "科举制度确立的见证",
      ],
    },
  ],
  materials: {
    ForbiddenCity: {
      wood: 200000,
      brick: 5000000,
      tile: 1500000,
    },
  },
  craftTimeline: [
    { year: -500, dynasty: "春秋", craft: "斗拱", event: "斗拱雏形出现" },
    { year: -200, dynasty: "汉", craft: "榫卯", event: "榫卯技术成熟" },
    { year: 600, dynasty: "唐", craft: "斗拱", event: "斗拱发展至鼎盛" },
    { year: 1100, dynasty: "宋", craft: "彩绘", event: "《营造法式》颁布" },
    { year: 1400, dynasty: "明", craft: "斗拱", event: "斗拱装饰化" },
  ],
  achievements: {
    ForbiddenCity: { scale: 95, craft: 90, preservation: 90, influence: 98 },
    Daming: { scale: 98, craft: 85, preservation: 30, influence: 85 },
    Weiyang: { scale: 100, craft: 75, preservation: 20, influence: 80 },
  },
  influence: {
    palace: 80,
    government: 70,
    international: 40,
  },
};

export const carouselData = [
  {
    id: 1,
    title: "明清紫禁城",
    description:
      "世界现存规模最大、保存最为完整的木质结构古建筑群，是中国古代宫廷文化的巅峰之作。",
    dynasty: "明、清",
    area: "72万平方米",
    image: new URL("../assets/images/明清紫禁城1.jpg", import.meta.url).href,
    route: "/overview",
  },
  {
    id: 2,
    title: "唐代大明宫",
    description:
      "盛唐时期的皇宫典范，中国古代宫殿建筑的巅峰之作，见证了唐朝的繁荣与辉煌。",
    dynasty: "唐",
    area: "320万平方米",
    image: new URL("../assets/images/唐代大明宫1.jpg", import.meta.url).href,
    route: "/layout",
  },
  {
    id: 3,
    title: "隋代大兴宫",
    description: "隋唐盛世的开端，中国古代宫殿建筑从秦汉向盛唐过渡的重要见证。",
    dynasty: "隋",
    area: "192万平方米",
    image: new URL("../assets/images/隋代大兴宫1.jpg", import.meta.url).href,
    route: "/craft",
  },
  {
    id: 4,
    title: "汉代未央宫",
    description:
      "丝绸之路的起点，西汉帝国的政治文化中心，中国古代宫殿的典范之作。",
    dynasty: "汉",
    area: "484万平方米",
    image: new URL("../assets/images/未央宫1.jpg", import.meta.url).href,
    route: "/craft",
  },
  {
    id: 5,
    title: "宋代东京皇宫",
    description: "繁华市井与皇家园林的完美融合，展现了宋代高度发达的城市文明。",
    dynasty: "北宋",
    area: "250万平方米",
    image: new URL("../assets/images/宋代东京皇宫1.jpg", import.meta.url).href,
    route: "/achievement",
  },
  {
    id: 6,
    title: "元代大都皇宫",
    description:
      "元朝帝国的政治中心，展现了蒙古族与汉族文化交融的独特建筑风格。",
    dynasty: "元",
    area: "480万平方米",
    image: new URL("../assets/images/元代大都皇宫1.jpg", import.meta.url).href,
    route: "/achievement",
  },
];
